using System;
namespace HelloRemoting1
{
	public enum EXTEND_CMD_ID : ushort
	{
		SYNC_DEV_LIST = 4337,
		UPDATE_DEV_LIST_STATUE,
		ADD_DEVICE_TO_LIST,
		DEL_DEVICE_FROM_LIST,
		HEART_TRIGGER_UPDATE,
		HEART_TRIGGER_ADD,
		OFFLINE_TRIGGER_UPDATE,
		SET_ALL_PWD,
		SEND_NET_PARA_CONFIG,
		ADD_DEV_INFO_NOCHECK,
		REPLACE_DEV_INFO_NOCHECK,
		SET_ENABLE_DEVICE,
		MODIFY_TCP_PORT,
		MODIFY_UDP_PORT,
		HEART_ONOFF
	}
}
